spring: 
  profiles:
    active:
    - dev
---
server:
  port: 1001
  context-path: /
  
# 数据源配置
spring:
  profiles: dev
  application: 
    name: distribute-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_distribute?serverTimezone=UTC
    username: root
    password: zhang123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
     
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: distribute-student  #客户端服务名
    instance-id: distribute-student:1001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
       
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110
---
server:
  port: 1001
  context-path: /
  
# 数据源配置
spring:
  profiles: test
  application: 
    name: distribute-student
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_distribute?serverTimezone=UTC
    username: root
    password: zhang123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
     
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: distribute-student  #客户端服务名
    instance-id: distribute-student:1001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
       
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110
